#!/bin/bash
# ================================================================
# Opt IT — Phase 4 Security + Container Modules Setup
# Run from inside your opt-it-modules directory:
#   cd opt-it-modules
#   bash setup-phase4-modules.sh
# ================================================================

set -e

echo "================================================================"
echo "  Opt IT — Creating Phase 4 Security + Container modules"
echo "================================================================"

# ────────────────────────────────────────────────────────────────
# DIRECTORY STRUCTURE
# ────────────────────────────────────────────────────────────────

mkdir -p security/trivy
mkdir -p security/owasp
mkdir -p security/github-actions

mkdir -p containers/dockerfiles
mkdir -p containers/docker-compose
mkdir -p containers/kubernetes/base
mkdir -p containers/helm/templates

# ════════════════════════════════════════════════════════════════
# SECURITY MODULES
# ════════════════════════════════════════════════════════════════

# ────────────────────────────────────────────────────────────────
# TRIVY CONFIG
# Trivy scans containers, IaC, and filesystems for vulnerabilities
# ────────────────────────────────────────────────────────────────

cat > security/trivy/.trivyignore << 'EOF'
# ================================================================
# Trivy Ignore File — ${{ values.client_name }}
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# Add CVE IDs here to suppress known false positives.
# Format: one CVE ID per line
# Example: CVE-2021-44228
# ================================================================

# Add suppressed CVEs below this line:
EOF

cat > security/trivy/trivy.yaml << 'EOF'
# ================================================================
# Trivy Configuration — ${{ values.client_name }}
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

# Severity levels to report
severity:
  - CRITICAL
  - HIGH
${% if values.include_medium_severity %}
  - MEDIUM
${% endif %}

# Exit code when vulnerabilities are found
# 0 = always pass (report only), 1 = fail on findings
exit-code: ${{ values.trivy_exit_code }}

# Ignore unfixed vulnerabilities
ignore-unfixed: ${{ values.ignore_unfixed }}

# Output format: table, json, sarif, cyclonedx
format: table

# Scan types
scanners:
  - vuln
  - secret
  - misconfig

# Cache directory
cache:
  dir: /tmp/trivy-cache
EOF

# ────────────────────────────────────────────────────────────────
# TRIVY GITHUB ACTIONS WORKFLOW
# ────────────────────────────────────────────────────────────────

cat > security/github-actions/trivy-scan.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Trivy Security Scan
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

name: Security Scan — Trivy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run every day at 2am UTC
    - cron: '0 2 * * *'

jobs:
  trivy-fs-scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: security/trivy/trivy.yaml
          ignore-unfixed: ${{ values.ignore_unfixed }}
          severity: 'CRITICAL,HIGH${% if values.include_medium_severity %},MEDIUM${% endif %}'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'

      - name: Upload Trivy filesystem scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-fs-results.sarif'
          category: 'trivy-filesystem'

${% if values.scan_docker_image %}
  trivy-image-scan:
    name: Trivy Container Image Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ values.client_name }}:${{ '${{ github.sha }}' }} .

      - name: Run Trivy container image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ values.client_name }}:${{ "${{ github.sha }}" }}'
          trivy-config: security/trivy/trivy.yaml
          ignore-unfixed: ${{ values.ignore_unfixed }}
          severity: 'CRITICAL,HIGH${% if values.include_medium_severity %},MEDIUM${% endif %}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'

      - name: Upload Trivy image scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'trivy-container'
${% endif %}

${% if values.scan_iac %}
  trivy-iac-scan:
    name: Trivy IaC Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy IaC scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: './terraform'
          trivy-config: security/trivy/trivy.yaml
          severity: 'CRITICAL,HIGH${% if values.include_medium_severity %},MEDIUM${% endif %}'
          format: 'sarif'
          output: 'trivy-iac-results.sarif'

      - name: Upload Trivy IaC scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-iac-results.sarif'
          category: 'trivy-iac'
${% endif %}
EOF

# ────────────────────────────────────────────────────────────────
# OWASP DEPENDENCY CHECK
# ────────────────────────────────────────────────────────────────

cat > security/owasp/dependency-check.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — OWASP Dependency Check
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# Scans project dependencies for known CVEs using the NVD database.
# ================================================================

name: OWASP Dependency Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 3am UTC

jobs:
  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: '${{ values.client_name }}'
          path: '.'
          format: 'HTML,SARIF'
          out: 'reports'
          args: >
            --enableRetired
            --failOnCVSS ${{ values.owasp_fail_cvss }}
            --suppression security/owasp/suppressions.xml

      - name: Upload OWASP results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/dependency-check-report.sarif

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: owasp-dependency-check-report
          path: reports/dependency-check-report.html
          retention-days: 30
EOF

cat > security/owasp/suppressions.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!--
  OWASP Dependency Check Suppressions — ${{ values.client_name }}
  Generated by Opt IT Backstage — DO NOT EDIT MANUALLY

  Add suppression entries here for known false positives.
  See: https://jeremylong.github.io/DependencyCheck/general/suppression.html
-->
<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
  <!--
  Example suppression:
  <suppress>
    <notes>False positive - this CVE does not apply to our usage</notes>
    <cve>CVE-2021-44228</cve>
  </suppress>
  -->
</suppressions>
EOF

echo "✅ Security modules created"

# ════════════════════════════════════════════════════════════════
# CONTAINER MODULES
# ════════════════════════════════════════════════════════════════

# ────────────────────────────────────────────────────────────────
# DOCKERFILES — one per language, multi-stage builds
# ────────────────────────────────────────────────────────────────

cat > containers/dockerfiles/Dockerfile.nodejs << 'EOF'
# ================================================================
# ${{ values.client_name }} — Node.js Dockerfile
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# Multi-stage build:
#   Stage 1 (builder) — install dependencies and build
#   Stage 2 (production) — minimal runtime image
# ================================================================

# ── STAGE 1: Builder ─────────────────────────────────────────────
FROM node:${{ values.runtime_version }}-alpine AS builder

WORKDIR /app

# Copy package files first for better layer caching
COPY package*.json ./

# Install all dependencies including devDependencies for build
RUN npm ci

# Copy source code
COPY . .

# Build the application
RUN npm run build

# ── STAGE 2: Production ──────────────────────────────────────────
FROM node:${{ values.runtime_version }}-alpine AS production

WORKDIR /app

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs && \
    adduser -S -u 1001 -G nodejs nodejs

# Copy package files
COPY package*.json ./

# Install production dependencies only
RUN npm ci --only=production && \
    npm cache clean --force

# Copy built application from builder stage
COPY --from=builder /app/dist ./dist

# Change ownership to non-root user
RUN chown -R nodejs:nodejs /app

USER nodejs

# Expose application port
EXPOSE ${{ values.app_port }}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD node -e "require('http').get('http://localhost:${{ values.app_port }}${{ values.health_check_path }}', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"

# Start the application
CMD ["node", "dist/index.js"]
EOF

cat > containers/dockerfiles/Dockerfile.python << 'EOF'
# ================================================================
# ${{ values.client_name }} — Python Dockerfile
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

# ── STAGE 1: Builder ─────────────────────────────────────────────
FROM python:${{ values.runtime_version }}-slim AS builder

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first for layer caching
COPY requirements.txt .

# Install dependencies into a virtual environment
RUN python -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir --upgrade pip && \
    /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

# ── STAGE 2: Production ──────────────────────────────────────────
FROM python:${{ values.runtime_version }}-slim AS production

WORKDIR /app

# Create non-root user
RUN groupadd -g 1001 appuser && \
    useradd -u 1001 -g appuser -s /bin/sh appuser

# Copy virtual environment from builder
COPY --from=builder /opt/venv /opt/venv

# Copy application code
COPY --chown=appuser:appuser . .

# Activate virtual environment
ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

USER appuser

EXPOSE ${{ values.app_port }}

HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:${{ values.app_port }}${{ values.health_check_path }}')"

CMD ["python", "-m", "gunicorn", "--bind", "0.0.0.0:${{ values.app_port }}", "app:app"]
EOF

cat > containers/dockerfiles/Dockerfile.java << 'EOF'
# ================================================================
# ${{ values.client_name }} — Java Dockerfile
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

# ── STAGE 1: Builder ─────────────────────────────────────────────
FROM maven:3.9-eclipse-temurin-${{ values.runtime_version }} AS builder

WORKDIR /app

# Copy Maven files first for layer caching
COPY pom.xml .
COPY .mvn .mvn

# Download dependencies
RUN mvn dependency:go-offline -B

# Copy source and build
COPY src ./src
RUN mvn clean package -DskipTests -B

# ── STAGE 2: Production ──────────────────────────────────────────
FROM eclipse-temurin:${{ values.runtime_version }}-jre-alpine AS production

WORKDIR /app

# Create non-root user
RUN addgroup -g 1001 -S javauser && \
    adduser -S -u 1001 -G javauser javauser

# Copy JAR from builder
COPY --from=builder /app/target/*.jar app.jar
RUN chown javauser:javauser app.jar

USER javauser

EXPOSE ${{ values.app_port }}

# JVM tuning for containers
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:${{ values.app_port }}${{ values.health_check_path }} || exit 1

CMD ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
EOF

cat > containers/dockerfiles/Dockerfile.go << 'EOF'
# ================================================================
# ${{ values.client_name }} — Go Dockerfile
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

# ── STAGE 1: Builder ─────────────────────────────────────────────
FROM golang:${{ values.runtime_version }}-alpine AS builder

WORKDIR /app

# Copy go module files first for layer caching
COPY go.mod go.sum ./
RUN go mod download

# Copy source and build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags="-w -s" \
    -o /app/server \
    ./cmd/server

# ── STAGE 2: Production (distroless for Go — smallest possible image) ──
FROM gcr.io/distroless/static-debian12 AS production

WORKDIR /app

# Copy binary from builder
COPY --from=builder /app/server .

# Distroless runs as nonroot by default (uid 65532)
USER nonroot:nonroot

EXPOSE ${{ values.app_port }}

CMD ["/app/server"]
EOF

echo "✅ Dockerfiles created"

# ────────────────────────────────────────────────────────────────
# DOCKER COMPOSE — local development
# ────────────────────────────────────────────────────────────────

cat > containers/docker-compose/docker-compose.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Docker Compose (Local Development)
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# Usage:
#   docker compose up -d
#   docker compose logs -f app
#   docker compose down
# ================================================================

version: "3.8"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

services:

  app:
    build:
      context: ../..
      dockerfile: containers/dockerfiles/Dockerfile.${{ values.language }}
    container_name: ${{ values.client_name }}-app
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "${{ values.app_port }}:${{ values.app_port }}"
    environment:
      NODE_ENV: development
      PORT: "${{ values.app_port }}"
      DATABASE_URL: "${{ values.db_connection_string }}"
    depends_on:
      db:
        condition: service_healthy
    labels:
      client: ${{ values.client_name }}
      environment: local
      managed-by: opt-it-backstage

${% if values.include_database %}
  db:
    image: ${% if values.db_engine == 'postgres' %}postgres:15-alpine${% else %}mysql:8.0${% endif %}
    container_name: ${{ values.client_name }}-db
    restart: unless-stopped
    networks:
      - app-network
    environment:
${% if values.db_engine == 'postgres' %}
      POSTGRES_DB: ${{ values.db_name }}
      POSTGRES_USER: ${{ values.db_user }}
      POSTGRES_PASSWORD: ${{ values.db_password }}
${% else %}
      MYSQL_DATABASE: ${{ values.db_name }}
      MYSQL_USER: ${{ values.db_user }}
      MYSQL_PASSWORD: ${{ values.db_password }}
      MYSQL_ROOT_PASSWORD: ${{ values.db_password }}
${% endif %}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
${% if values.db_engine == 'postgres' %}
      test: ["CMD-SHELL", "pg_isready -U ${{ values.db_user }} -d ${{ values.db_name }}"]
${% else %}
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
${% endif %}
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      client: ${{ values.client_name }}
      managed-by: opt-it-backstage
${% endif %}

${% if values.include_redis %}
  redis:
    image: redis:7-alpine
    container_name: ${{ values.client_name }}-redis
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      client: ${{ values.client_name }}
      managed-by: opt-it-backstage
${% endif %}
EOF

echo "✅ Docker Compose created"

# ────────────────────────────────────────────────────────────────
# KUBERNETES MANIFESTS
# ────────────────────────────────────────────────────────────────

cat > containers/kubernetes/base/namespace.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Kubernetes Namespace
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: ${{ values.k8s_namespace }}
  labels:
    client: ${{ values.client_name }}
    environment: ${{ values.environment }}
    managed-by: opt-it-backstage
EOF

cat > containers/kubernetes/base/deployment.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Kubernetes Deployment
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.client_name }}-app
  namespace: ${{ values.k8s_namespace }}
  labels:
    app: ${{ values.client_name }}
    environment: ${{ values.environment }}
    managed-by: opt-it-backstage
spec:
  replicas: ${{ values.initial_replicas }}
  selector:
    matchLabels:
      app: ${{ values.client_name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ${{ values.client_name }}
        environment: ${{ values.environment }}
    spec:
      # Security context — run as non-root
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001

      containers:
        - name: app
          image: ${{ values.container_registry }}/${{ values.client_name }}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: ${{ values.app_port }}
              protocol: TCP

          # Resource limits — always set to prevent noisy neighbours
          resources:
            requests:
              cpu: ${{ values.cpu_request }}
              memory: ${{ values.memory_request }}
            limits:
              cpu: ${{ values.cpu_limit }}
              memory: ${{ values.memory_limit }}

          # Liveness probe — restarts container if unhealthy
          livenessProbe:
            httpGet:
              path: ${{ values.health_check_path }}
              port: ${{ values.app_port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          # Readiness probe — removes from load balancer if not ready
          readinessProbe:
            httpGet:
              path: ${{ values.health_check_path }}
              port: ${{ values.app_port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          # Environment variables from ConfigMap and Secret
          envFrom:
            - configMapRef:
                name: ${{ values.client_name }}-config
            - secretRef:
                name: ${{ values.client_name }}-secrets

          # Container security context
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

      # Ensure pods spread across nodes
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ${{ values.client_name }}
EOF

cat > containers/kubernetes/base/service.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Kubernetes Service
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

apiVersion: v1
kind: Service
metadata:
  name: ${{ values.client_name }}-svc
  namespace: ${{ values.k8s_namespace }}
  labels:
    app: ${{ values.client_name }}
    managed-by: opt-it-backstage
spec:
  selector:
    app: ${{ values.client_name }}
  ports:
    - name: http
      port: 80
      targetPort: ${{ values.app_port }}
      protocol: TCP
  type: ClusterIP
EOF

cat > containers/kubernetes/base/ingress.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Kubernetes Ingress
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.client_name }}-ingress
  namespace: ${{ values.k8s_namespace }}
  labels:
    app: ${{ values.client_name }}
    managed-by: opt-it-backstage
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${{ values.domain }}
      secretName: ${{ values.client_name }}-tls
  rules:
    - host: ${{ values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.client_name }}-svc
                port:
                  number: 80
EOF

cat > containers/kubernetes/base/hpa.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Horizontal Pod Autoscaler
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${{ values.client_name }}-hpa
  namespace: ${{ values.k8s_namespace }}
  labels:
    app: ${{ values.client_name }}
    managed-by: opt-it-backstage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${{ values.client_name }}-app
  minReplicas: ${{ values.min_replicas }}
  maxReplicas: ${{ values.max_replicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${{ values.cpu_target_utilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
EOF

cat > containers/kubernetes/base/configmap.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — ConfigMap
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# Non-sensitive configuration values.
# For sensitive values, use the Secret manifest below.
# ================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.client_name }}-config
  namespace: ${{ values.k8s_namespace }}
  labels:
    app: ${{ values.client_name }}
    managed-by: opt-it-backstage
data:
  NODE_ENV: "${{ values.environment }}"
  PORT: "${{ values.app_port }}"
  LOG_LEVEL: "${% if values.environment == 'prod' %}info${% else %}debug${% endif %}"
  # Add your non-sensitive config values here
EOF

cat > containers/kubernetes/base/secret.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Secret Template
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# ⚠️ DO NOT commit real secret values to Git.
# This file is a template only. Populate secrets using:
#   - kubectl create secret generic
#   - External Secrets Operator
#   - Sealed Secrets
#   - HashiCorp Vault
# ================================================================

apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.client_name }}-secrets
  namespace: ${{ values.k8s_namespace }}
  labels:
    app: ${{ values.client_name }}
    managed-by: opt-it-backstage
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_WITH_REAL_VALUE"
  API_KEY: "REPLACE_WITH_REAL_VALUE"
  # Add your secret keys here — values will be base64 encoded by Kubernetes
EOF

echo "✅ Kubernetes manifests created"

# ────────────────────────────────────────────────────────────────
# HELM CHART
# ────────────────────────────────────────────────────────────────

cat > containers/helm/Chart.yaml << 'EOF'
apiVersion: v2
name: ${{ values.client_name }}
description: Helm chart for ${{ values.client_name }} — generated by Opt IT Backstage
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Opt IT Technologies
    email: devops@opt-it.com
EOF

cat > containers/helm/values.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Helm Default Values
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# Override these values per environment:
#   helm install ${{ values.client_name }} . -f values.prod.yaml
# ================================================================

replicaCount: ${{ values.initial_replicas }}

image:
  repository: ${{ values.container_registry }}/${{ values.client_name }}
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: ${{ values.app_port }}

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ${{ values.domain }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ${{ values.client_name }}-tls
      hosts:
        - ${{ values.domain }}

resources:
  requests:
    cpu: ${{ values.cpu_request }}
    memory: ${{ values.memory_request }}
  limits:
    cpu: ${{ values.cpu_limit }}
    memory: ${{ values.memory_limit }}

autoscaling:
  enabled: true
  minReplicas: ${{ values.min_replicas }}
  maxReplicas: ${{ values.max_replicas }}
  targetCPUUtilizationPercentage: ${{ values.cpu_target_utilization }}

probes:
  liveness:
    path: ${{ values.health_check_path }}
    initialDelaySeconds: 30
  readiness:
    path: ${{ values.health_check_path }}
    initialDelaySeconds: 10

env:
  NODE_ENV: ${{ values.environment }}
  PORT: "${{ values.app_port }}"

namespace: ${{ values.k8s_namespace }}
EOF

cat > containers/helm/templates/deployment.yaml << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "${{ values.client_name }}.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "${{ values.client_name }}.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "${{ values.client_name }}.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "${{ values.client_name }}.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          envFrom:
            - configMapRef:
                name: {{ include "${{ values.client_name }}.fullname" . }}-config
            - secretRef:
                name: {{ include "${{ values.client_name }}.fullname" . }}-secrets
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
EOF

cat > containers/helm/templates/_helpers.tpl << 'EOF'
{{/*
Expand the name of the chart.
*/}}
{{- define "${{ values.client_name }}.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "${{ values.client_name }}.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "${{ values.client_name }}.labels" -}}
helm.sh/chart: {{ include "${{ values.client_name }}.name" . }}-{{ .Chart.Version }}
{{ include "${{ values.client_name }}.selectorLabels" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
managed-by: opt-it-backstage
{{- end }}

{{/*
Selector labels
*/}}
{{- define "${{ values.client_name }}.selectorLabels" -}}
app.kubernetes.io/name: {{ include "${{ values.client_name }}.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
EOF

echo "✅ Helm chart created"

# ────────────────────────────────────────────────────────────────
# COMMIT AND PUSH
# ────────────────────────────────────────────────────────────────

echo ""
echo "================================================================"
echo "  Committing and pushing Phase 4 modules..."
echo "================================================================"

git add security/ containers/
git commit -m "feat(phase4): add security scanning and container modules"
git push origin main

echo ""
echo "================================================================"
echo "  ✅ Phase 4 modules pushed!"
echo ""
echo "  Security modules:"
echo "    security/trivy/"
echo "    security/owasp/"
echo "    security/github-actions/"
echo ""
echo "  Container modules:"
echo "    containers/dockerfiles/ (Node.js, Python, Java, Go)"
echo "    containers/docker-compose/"
echo "    containers/kubernetes/base/"
echo "    containers/helm/"
echo "================================================================"