#!/bin/bash
# ================================================================
# Opt IT — Phase 3 CI/CD Modules Setup
# Run from inside your opt-it-modules directory:
#   cd opt-it-modules
#   bash setup-cicd-modules.sh
# ================================================================

set -e

echo "================================================================"
echo "  Opt IT — Creating Phase 3 CI/CD modules"
echo "================================================================"

mkdir -p cicd/gitlab-ci
mkdir -p cicd/argocd/base
mkdir -p cicd/github-actions/workflows

# ────────────────────────────────────────────────────────────────
# GITLAB CI
# ────────────────────────────────────────────────────────────────

cat > cicd/gitlab-ci/.gitlab-ci.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — GitLab CI Pipeline
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

# ── BUILD ────────────────────────────────────────────────────────

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - main
    - develop
    - merge_requests

# ── TEST ─────────────────────────────────────────────────────────

test:unit:
  stage: test
  image: node:20-alpine
  script:
    - npm ci
    - npm test
  coverage: '/Lines\s*:\s*(\d+\.?\d*)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  only:
    - main
    - develop
    - merge_requests

test:lint:
  stage: test
  image: node:20-alpine
  script:
    - npm ci
    - npm run lint
  only:
    - main
    - develop
    - merge_requests

# ── DEPLOY ───────────────────────────────────────────────────────

deploy:staging:
  stage: deploy
  image: alpine:latest
  environment:
    name: staging
    url: https://staging.${{ values.client_name }}.example.com
  script:
    - echo "Deploy to staging"
    # Add your deployment commands here
    # Example: kubectl set image deployment/app app=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - develop

deploy:production:
  stage: deploy
  image: alpine:latest
  environment:
    name: production
    url: https://${{ values.client_name }}.example.com
  script:
    - echo "Deploy to production"
    # Add your deployment commands here
  when: manual  # requires manual approval for production
  only:
    - main
EOF

echo "✅ GitLab CI template created"

# ────────────────────────────────────────────────────────────────
# ARGOCD
# ArgoCD is GitOps — it syncs Kubernetes manifests from a Git repo
# These are the ArgoCD Application and AppProject manifests
# ────────────────────────────────────────────────────────────────

cat > cicd/argocd/base/app-project.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — ArgoCD AppProject
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# An AppProject defines boundaries for an ArgoCD Application:
# - Which Git repos can be used as sources
# - Which clusters can be deployed to
# - Which namespaces are allowed
# ================================================================

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{ values.client_name }}-${{ values.environment }}
  namespace: argocd
  labels:
    client: ${{ values.client_name }}
    environment: ${{ values.environment }}
    managed-by: opt-it-backstage
spec:
  description: "ArgoCD project for ${{ values.client_name }} ${{ values.environment }}"

  # Source repos this project can use
  sourceRepos:
    - "${{ values.repo_url }}"

  # Destination clusters and namespaces
  destinations:
    - namespace: ${{ values.app_namespace }}
      server: ${{ values.cluster_url }}

  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: ReplicaSet
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "autoscaling"
      kind: HorizontalPodAutoscaler
EOF

cat > cicd/argocd/base/application.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — ArgoCD Application
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# An ArgoCD Application defines:
# - WHERE to get the manifests (source Git repo + path)
# - WHERE to deploy them (destination cluster + namespace)
# - HOW to sync (automatic or manual, prune, self-heal)
# ================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.client_name }}-${{ values.environment }}
  namespace: argocd
  labels:
    client: ${{ values.client_name }}
    environment: ${{ values.environment }}
    managed-by: opt-it-backstage
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # cascade delete on app removal
spec:
  project: ${{ values.client_name }}-${{ values.environment }}

  source:
    repoURL: ${{ values.repo_url }}
    targetRevision: ${{ values.target_revision }}
    path: ${{ values.manifests_path }}

  destination:
    server: ${{ values.cluster_url }}
    namespace: ${{ values.app_namespace }}

  syncPolicy:
    automated:
      prune: ${{ values.argocd_prune }}        # delete resources not in Git
      selfHeal: ${{ values.argocd_self_heal }}  # revert manual changes
    syncOptions:
      - CreateNamespace=true   # auto-create namespace if missing
      - PrunePropagationPolicy=foreground
      - PruneLast=true

  # Health check overrides
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # ignore replica count (managed by HPA)
EOF

cat > cicd/argocd/base/namespace.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Application Namespace
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: ${{ values.app_namespace }}
  labels:
    client: ${{ values.client_name }}
    environment: ${{ values.environment }}
    managed-by: opt-it-backstage
EOF

echo "✅ ArgoCD templates created"

# ────────────────────────────────────────────────────────────────
# EXPAND GITHUB ACTIONS
# Add more workflow templates
# ────────────────────────────────────────────────────────────────

cat > cicd/github-actions/workflows/build.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Build Workflow
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 7
EOF

cat > cicd/github-actions/workflows/test.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Test Workflow
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
EOF

cat > cicd/github-actions/workflows/deploy.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Deploy Workflow
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options: [staging, production]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "Deploying ${{ values.client_name }} to staging"
          # Add your deployment commands here

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-staging
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying ${{ values.client_name }} to production"
          # Add your deployment commands here
EOF

echo "✅ GitHub Actions workflows expanded"

# ────────────────────────────────────────────────────────────────
# EXPAND JENKINS
# ────────────────────────────────────────────────────────────────

cat > cicd/jenkins/Jenkinsfile << 'EOF'
// ================================================================
// ${{ values.client_name }} — Jenkins Pipeline
// Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
// ================================================================

pipeline {
    agent {
        docker {
            image 'node:20-alpine'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        CLIENT_NAME = '${{ values.client_name }}'
        APP_ENV     = '${{ values.environment }}'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }

    stages {

        stage('Install') {
            steps {
                sh 'npm ci'
            }
        }

        stage('Lint') {
            steps {
                sh 'npm run lint'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test -- --coverage'
            }
            post {
                always {
                    junit 'coverage/junit.xml'
                }
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Deploy Staging') {
            when {
                branch 'develop'
            }
            steps {
                echo "Deploying ${CLIENT_NAME} to staging"
                // Add your deployment commands here
            }
        }

        stage('Deploy Production') {
            when {
                branch 'main'
            }
            input {
                message "Deploy ${CLIENT_NAME} to production?"
                ok "Deploy"
            }
            steps {
                echo "Deploying ${CLIENT_NAME} to production"
                // Add your deployment commands here
            }
        }
    }

    post {
        success {
            echo "Pipeline succeeded for ${CLIENT_NAME}"
        }
        failure {
            echo "Pipeline failed for ${CLIENT_NAME} — check logs above"
        }
        always {
            cleanWs()
        }
    }
}
EOF

echo "✅ Jenkins pipeline expanded"

# ────────────────────────────────────────────────────────────────
# COMMIT AND PUSH
# ────────────────────────────────────────────────────────────────

echo ""
echo "================================================================"
echo "  Committing and pushing CI/CD modules..."
echo "================================================================"

git add cicd/
git commit -m "feat(cicd): add gitlab-ci, argocd, expand github-actions and jenkins"
git push origin main

echo ""
echo "================================================================"
echo "  ✅ CI/CD modules pushed!"
echo "================================================================"