#!/bin/bash
# ================================================================
# Opt IT — Phase 3 Observability Modules Setup
# Run from inside your opt-it-modules directory:
#   cd opt-it-modules
#   bash setup-observability-modules.sh
# ================================================================

set -e

echo "================================================================"
echo "  Opt IT — Creating Observability modules (Prometheus + Grafana)"
echo "================================================================"

mkdir -p observability/prometheus/alert-rules
mkdir -p observability/grafana/provisioning/datasources
mkdir -p observability/grafana/provisioning/dashboards
mkdir -p observability/grafana/dashboards
mkdir -p observability/docker-compose
mkdir -p observability/helm/templates

# ────────────────────────────────────────────────────────────────
# PROMETHEUS CONFIG
# ────────────────────────────────────────────────────────────────

cat > observability/prometheus/prometheus.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Prometheus Configuration
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

global:
  scrape_interval:     ${{ values.scrape_interval }}
  evaluation_interval: ${{ values.scrape_interval }}
  external_labels:
    client:      '${{ values.client_name }}'
    environment: '${{ values.environment }}'
    managed_by:  'opt-it-backstage'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alert rules
rule_files:
  - /etc/prometheus/alert-rules/*.yml

# ── SCRAPE CONFIGS ───────────────────────────────────────────────

scrape_configs:

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter — host metrics (CPU, memory, disk, network)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # Blackbox Exporter — HTTP endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://localhost:80/health  # replace with your app health endpoint
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

${% if values.scrape_app_metrics %}
  # Application metrics — customize this endpoint
  - job_name: '${{ values.client_name }}-app'
    static_configs:
      - targets: ['app:${{ values.app_metrics_port }}']
    metrics_path: '/metrics'
${% endif %}
EOF

cat > observability/prometheus/alert-rules/infra-alerts.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Infrastructure Alert Rules
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

groups:
  - name: infrastructure
    rules:

      # CPU
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: warning
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | humanize }}% for more than 5 minutes."

      - alert: CriticalCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 2m
        labels:
          severity: critical
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "Critical CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | humanize }}% for more than 2 minutes."

      # Memory
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value | humanize }}%."

      # Disk
      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 80
        for: 5m
        labels:
          severity: warning
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk {{ $labels.mountpoint }} is {{ $value | humanize }}% full."

      - alert: DiskSpaceCritical
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
        for: 2m
        labels:
          severity: critical
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "Critical disk space on {{ $labels.instance }}"
          description: "Disk {{ $labels.mountpoint }} is {{ $value | humanize }}% full."

      # Instance down
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} has been down for more than 1 minute."
EOF

cat > observability/prometheus/alert-rules/app-alerts.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Application Alert Rules
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

groups:
  - name: application
    rules:

      # HTTP error rate
      - alert: HighHTTPErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "High HTTP error rate"
          description: "HTTP 5xx error rate is {{ $value | humanizePercentage }}."

      # HTTP latency
      - alert: HighHTTPLatency
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "High HTTP latency"
          description: "99th percentile latency is {{ $value | humanizeDuration }}."

      # Endpoint down
      - alert: EndpointDown
        expr: probe_success == 0
        for: 2m
        labels:
          severity: critical
          client: ${{ values.client_name }}
          environment: ${{ values.environment }}
        annotations:
          summary: "Endpoint {{ $labels.instance }} is down"
          description: "HTTP probe failed for {{ $labels.instance }}."
EOF

echo "✅ Prometheus configs created"

# ────────────────────────────────────────────────────────────────
# GRAFANA CONFIG
# ────────────────────────────────────────────────────────────────

cat > observability/grafana/grafana.ini << 'EOF'
# ================================================================
# ${{ values.client_name }} — Grafana Configuration
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

[server]
root_url = http://localhost:${{ values.grafana_port }}

[security]
admin_user     = admin
admin_password = ${{ values.grafana_admin_password }}
# Change this password immediately after first login

[auth.anonymous]
enabled = false

[users]
allow_sign_up = false

[alerting]
enabled = true

[smtp]
${% if values.alert_email %}
enabled  = true
host     = smtp.gmail.com:587
from_address = alerts@${{ values.client_name }}.example.com
${% else %}
enabled  = false
${% endif %}

[log]
mode  = console
level = info
EOF

cat > observability/grafana/provisioning/datasources/prometheus.yml << 'EOF'
# ================================================================
# Grafana Datasource — Prometheus
# Auto-provisioned by Opt IT Backstage
# ================================================================

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "${{ values.scrape_interval }}"
EOF

cat > observability/grafana/provisioning/dashboards/dashboard-provider.yml << 'EOF'
# ================================================================
# Grafana Dashboard Provider
# Auto-loads dashboards from /etc/grafana/dashboards/
# ================================================================

apiVersion: 1

providers:
  - name: 'Opt IT Dashboards'
    orgId: 1
    folder: '${{ values.client_name }}'
    type: file
    disableDeletion: true
    updateIntervalSeconds: 30
    allowUiUpdates: false
    options:
      path: /etc/grafana/dashboards
EOF

# Infrastructure overview dashboard (simplified JSON)
cat > observability/grafana/dashboards/infra-overview.json << 'EOF'
{
  "title": "${{ values.client_name }} — Infrastructure Overview",
  "tags": ["infrastructure", "${{ values.client_name }}", "${{ values.environment }}"],
  "timezone": "browser",
  "refresh": "30s",
  "panels": [
    {
      "id": 1,
      "title": "CPU Usage %",
      "type": "stat",
      "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
      "targets": [
        {
          "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
          "legendFormat": "CPU %"
        }
      ]
    },
    {
      "id": 2,
      "title": "Memory Usage %",
      "type": "stat",
      "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
      "targets": [
        {
          "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
          "legendFormat": "Memory %"
        }
      ]
    },
    {
      "id": 3,
      "title": "Disk Usage %",
      "type": "stat",
      "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
      "targets": [
        {
          "expr": "(1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})) * 100",
          "legendFormat": "Disk %"
        }
      ]
    },
    {
      "id": 4,
      "title": "CPU Usage Over Time",
      "type": "timeseries",
      "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
      "targets": [
        {
          "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
          "legendFormat": "{{ instance }}"
        }
      ]
    }
  ]
}
EOF

echo "✅ Grafana configs created"

# ────────────────────────────────────────────────────────────────
# DOCKER COMPOSE DEPLOYMENT
# ────────────────────────────────────────────────────────────────

cat > observability/docker-compose/docker-compose.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Observability Stack
# Docker Compose Deployment
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
#
# Usage:
#   docker compose up -d
#   Grafana: http://localhost:${{ values.grafana_port }}
#   Prometheus: http://localhost:9090
# ================================================================

version: "3.8"

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: ${{ values.client_name }}-prometheus
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert-rules:/etc/prometheus/alert-rules:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=${{ values.retention_days }}d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    labels:
      client: ${{ values.client_name }}
      environment: ${{ values.environment }}
      managed-by: opt-it-backstage

  grafana:
    image: grafana/grafana:10.2.0
    container_name: ${{ values.client_name }}-grafana
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "${{ values.grafana_port }}:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${{ values.grafana_admin_password }}
    depends_on:
      - prometheus
    labels:
      client: ${{ values.client_name }}
      environment: ${{ values.environment }}
      managed-by: opt-it-backstage

  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: ${{ values.client_name }}-node-exporter
    restart: unless-stopped
    networks:
      - monitoring
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    labels:
      client: ${{ values.client_name }}
      environment: ${{ values.environment }}
      managed-by: opt-it-backstage

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: ${{ values.client_name }}-alertmanager
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    labels:
      client: ${{ values.client_name }}
      environment: ${{ values.environment }}
      managed-by: opt-it-backstage

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.24.0
    container_name: ${{ values.client_name }}-blackbox
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - "9115:9115"
    labels:
      client: ${{ values.client_name }}
      environment: ${{ values.environment }}
      managed-by: opt-it-backstage
EOF

# ────────────────────────────────────────────────────────────────
# ALERTMANAGER CONFIG
# ────────────────────────────────────────────────────────────────

mkdir -p observability/alertmanager

cat > observability/alertmanager/alertmanager.yml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Alertmanager Configuration
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'client', 'environment']
  group_wait:      30s
  group_interval:  5m
  repeat_interval: 12h
  receiver: 'default'

  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      repeat_interval: 1h

receivers:

  - name: 'default'
${% if values.slack_webhook %}
    slack_configs:
      - api_url: '${{ values.slack_webhook }}'
        channel: '#${{ values.slack_channel }}'
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
${% else %}
    # Configure a notification channel above
    # Options: slack_configs, email_configs, pagerduty_configs
${% endif %}

  - name: 'critical-alerts'
${% if values.alert_email %}
    email_configs:
      - to: '${{ values.alert_email }}'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }} — ${{ values.client_name }}'
        body: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
${% endif %}
${% if values.slack_webhook %}
    slack_configs:
      - api_url: '${{ values.slack_webhook }}'
        channel: '#${{ values.slack_channel }}'
        title: '🚨 [CRITICAL] {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
${% endif %}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
EOF

echo "✅ Alertmanager config created"

# ────────────────────────────────────────────────────────────────
# HELM CHART
# ────────────────────────────────────────────────────────────────

cat > observability/helm/Chart.yaml << 'EOF'
apiVersion: v2
name: opt-it-observability
description: Opt IT observability stack — Prometheus + Grafana + Alertmanager
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: "25.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "7.x.x"
    repository: "https://grafana.github.io/helm-charts"
EOF

cat > observability/helm/values.yaml << 'EOF'
# ================================================================
# ${{ values.client_name }} — Observability Helm Values
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

global:
  labels:
    client: ${{ values.client_name }}
    environment: ${{ values.environment }}
    managed-by: opt-it-backstage

prometheus:
  server:
    retention: "${{ values.retention_days }}d"
    global:
      scrape_interval: ${{ values.scrape_interval }}
      external_labels:
        client: ${{ values.client_name }}
        environment: ${{ values.environment }}
  alertmanager:
    enabled: true

grafana:
  adminPassword: "${{ values.grafana_admin_password }}"
  persistence:
    enabled: true
    size: 5Gi
  service:
    port: ${{ values.grafana_port }}
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://{{ .Release.Name }}-prometheus-server
          isDefault: true
EOF

echo "✅ Helm chart created"

# ────────────────────────────────────────────────────────────────
# COMMIT AND PUSH
# ────────────────────────────────────────────────────────────────

echo ""
echo "================================================================"
echo "  Committing and pushing observability modules..."
echo "================================================================"

git add observability/
git commit -m "feat(observability): add Prometheus + Grafana stack with Docker Compose and Helm"
git push origin main

echo ""
echo "================================================================"
echo "  ✅ Observability modules pushed!"
echo "================================================================"