# ================================================================
# ${{ values.client_name }} — Java Dockerfile
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

# ── STAGE 1: Builder ─────────────────────────────────────────────
FROM maven:3.9-eclipse-temurin-${{ values.runtime_version }} AS builder

WORKDIR /app

# Copy Maven files first for layer caching
COPY pom.xml .
COPY .mvn .mvn

# Download dependencies
RUN mvn dependency:go-offline -B

# Copy source and build
COPY src ./src
RUN mvn clean package -DskipTests -B

# ── STAGE 2: Production ──────────────────────────────────────────
FROM eclipse-temurin:${{ values.runtime_version }}-jre-alpine AS production

WORKDIR /app

# Create non-root user
RUN addgroup -g 1001 -S javauser && \
    adduser -S -u 1001 -G javauser javauser

# Copy JAR from builder
COPY --from=builder /app/target/*.jar app.jar
RUN chown javauser:javauser app.jar

USER javauser

EXPOSE ${{ values.app_port }}

# JVM tuning for containers
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:${{ values.app_port }}${{ values.health_check_path }} || exit 1

CMD ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
