# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — AWS Infrastructure
# Generated by Opt IT Backstage on ${{ "" | now }}
# DO NOT EDIT MANUALLY — changes will be overwritten on next run
# ================================================================

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Uncomment and configure backend for remote state:
  # backend "s3" {
  #   bucket = "${{ values.client_name }}-${{ values.environment }}-tfstate"
  #   key    = "infrastructure/terraform.tfstate"
  #   region = "${{ values.aws_region }}"
  # }
}

provider "aws" {
  region = var.aws_region
}

# ────────────────────────────────────────────────────────────────
# VPC
# ${% if values.provision_vpc %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_vpc %}
module "vpc" {
  source = "./modules/vpc"

  client_name        = var.client_name
  environment        = var.environment
  module_version     = "1.0.0"
  aws_region         = var.aws_region
  vpc_cidr           = var.vpc_cidr
  enable_nat_gateway = var.environment == "prod" ? true : false
}

module "subnets" {
  source = "./modules/subnets"

  client_name         = var.client_name
  environment         = var.environment
  module_version      = "1.0.0"
  aws_region          = var.aws_region
  vpc_id              = module.vpc.vpc_id
  vpc_cidr            = module.vpc.vpc_cidr
  internet_gateway_id = module.vpc.internet_gateway_id
  nat_gateway_id      = module.vpc.nat_gateway_id
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# SECURITY GROUPS
# ${% if values.provision_ec2 or values.provision_rds %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_ec2 or values.provision_rds %}
module "security_groups" {
  source = "./modules/security-groups"

  client_name    = var.client_name
  environment    = var.environment
  module_version = "1.0.0"
  vpc_id         = module.vpc.vpc_id
  vpc_cidr       = module.vpc.vpc_cidr
  rds_port       = var.rds_engine == "mysql" ? 3306 : 5432
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# EC2
# ${% if values.provision_ec2 %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_ec2 %}
module "iam" {
  source = "./modules/iam-baseline"

  client_name        = var.client_name
  environment        = var.environment
  module_version     = "1.0.0"
  ${% if values.provision_s3 %}
  ec2_s3_bucket_arns = [
    module.s3.bucket_arn,
    "${module.s3.bucket_arn}/*"
  ]
  ${% endif %}
}

module "ec2" {
  source = "./modules/ec2"

  client_name        = var.client_name
  environment        = var.environment
  module_version     = "1.0.0"
  aws_region         = var.aws_region
  subnet_id          = module.subnets.private_subnet_ids[0]
  security_group_ids = [module.security_groups.web_security_group_id]
  instance_type      = var.ec2_instance_type
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# S3
# ${% if values.provision_s3 %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_s3 %}
module "s3" {
  source = "./modules/s3"

  client_name       = var.client_name
  environment       = var.environment
  module_version    = "1.0.0"
  bucket_suffix     = "storage"
  enable_versioning = ${{ values.s3_versioning }}
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# RDS
# ${% if values.provision_rds %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_rds %}
module "rds" {
  source = "./modules/rds"

  client_name        = var.client_name
  environment        = var.environment
  module_version     = "1.0.0"
  subnet_ids         = module.subnets.private_subnet_ids
  security_group_ids = [module.security_groups.database_security_group_id]
  engine             = var.rds_engine
  master_password    = var.db_master_password
}
${% endif %}
