# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — Outputs
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

${% if values.provision_vpc %}
output "vpc_id" {
  description = "VPC ID"
  value       = module.vpc.vpc_id
}
${% endif %}

${% if values.provision_ec2 %}
output "ec2_instance_id" {
  description = "EC2 instance ID"
  value       = module.ec2.instance_id
}

output "ec2_private_ip" {
  description = "EC2 private IP"
  value       = module.ec2.instance_private_ip
}
${% endif %}

${% if values.provision_s3 %}
output "s3_bucket_name" {
  description = "S3 bucket name"
  value       = module.s3.bucket_id
}

output "s3_bucket_arn" {
  description = "S3 bucket ARN"
  value       = module.s3.bucket_arn
}
${% endif %}

${% if values.provision_rds %}
output "rds_endpoint" {
  description = "RDS connection endpoint"
  value       = module.rds.db_endpoint
  sensitive   = true
}
${% endif %}
