# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — Variables
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

variable "client_name" {
  description = "Client name"
  type        = string
  default     = "${{ values.client_name }}"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "${{ values.environment }}"
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "${{ values.aws_region }}"
}

${% if values.provision_vpc %}
variable "vpc_cidr" {
  description = "VPC CIDR block"
  type        = string
  default     = "${{ values.vpc_cidr }}"
}
${% endif %}

${% if values.provision_ec2 %}
variable "ec2_instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "${{ values.ec2_instance_type }}"
}
${% endif %}

${% if values.provision_rds %}
variable "rds_engine" {
  description = "RDS database engine"
  type        = string
  default     = "${{ values.rds_engine }}"
}

variable "db_master_password" {
  description = "RDS master password — set via TF_VAR_db_master_password environment variable or GitHub Secret. Never hardcode."
  type        = string
  sensitive   = true
}
${% endif %}
